module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-unstable
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args: []
excluded-modules:
- conduit/benchmarks/OldText.hs
- network-conduit-tls/Data/Conduit/Network/TLS.hs
- network-conduit-tls/Data/Conduit/Network/TLS/Internal.hs
