sudo: false
language: c

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-1.22
            - ghc-7.4.2
            - ghc-7.6.3
            - ghc-7.8.4
            - ghc-7.10.1
            - ghc-7.10.2
            - ghc-7.10.3

env:
  global:
    - CABALVER=1.22
    - PACKAGE_LIST="./resourcet ./conduit ./network-conduit-tls ./conduit-extra ./cereal-conduit"
  matrix:
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=7.8.4
    - GHCVER=7.10.1
    - GHCVER=7.10.2
    - GHCVER=7.10.3

matrix:
  allow_failures:
    # Seems like Travis doesn't reliably have this yet
    - env: GHCVER=7.10.3

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

script:
 - cabal install --run-tests --enable-benchmarks --force-reinstalls $PACKAGE_LIST --reorder-goals --max-backjumps=-1
