language: haskell

install:
    - cabal update
    - cabal install hspec doctest cabal-meta cabal-src
    - cabal-meta install --force-reinstalls --only-dependencies --enable-tests
    - cabal-meta install --force-reinstalls

script: mega-sdist --test
